### ISSUE TITLE
Prepare for CRAN release

### ISSUE THREAD

**Issue by restonslacker** [mitre/Rsch#1]
1. [ ] get the java part sorted. 
      - [ ] remove `old` folder from inst\java
    - [ ] i think i need to add a `java` folder at the root level with the java source. research this
2. [ ] fix the `credentials` issue
   - [ ] option 1: bug @mattpollock to setup a `drat` repo for the package
   - [x] option 2: bug @mattpollock to submit to CRAN
   - [x] option 3: see if there's a newer alternative already on CRAN. something sticks in my mind.

**Comment by mattpollock** [comment]
I'd be interested to see the `credentials` alternative. I think there are some RStudio-specific ones, but I haven't seen a general use option.

I'll try to get `credentials` on CRAN within the next week.

**Comment by restonslacker** [comment]
It's called `getPass` https://github.com/wrathematics/getPass it doesn't do the user guessing, but otherwise is pretty similar. `credentials` actually has a couple of more options. maybe open an issue with getPass and ask about merging in those features? there's so much overlap it seems crazy to have both.

**Comment by mattpollock** [comment]
@restonslacker you're welcome to pick this up if you like, but it seems unlikely that either of us is going to get to it soon.

**Comment by restonslacker** [comment]
Yeah… there are probably better ways to do this now too.
